apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: file-read-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: file-read-app
subjects:
  - kind: ServiceAccount
    name: file-read-app