apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "application.fullname" . }}
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["create"]